- name: Deploy Supabase using Helm
  hosts: localhost
  tasks:
    - name: Add Supabase Helm repo
      shell: helm repo add supabase https://supabase-community.github.io/helm-charts && helm repo update

    - name: Install Supabase
      shell: helm install supabase supabase/supabase -n supabase --create-namespace
